apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-cert-manager
  name: kube-cert-manager
  namespace: {{ .Values.deploymentNamespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-cert-manager
      name: kube-cert-manager
    spec:
      containers:
        - name: kube-cert-manager
          image: palmstonegames/kube-cert-manager:{{ .Chart.Version }}
          env:
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                name: kube-cert-manager-environment
                key: cloudflare.email 
          args:
            - "-data-dir=/var/lib/cert-manager"
            - "-acme-url={{ .Values.acmeUrl }}"
          volumeMounts:
            - name: data
              mountPath: /var/lib/cert-manager
        - name: kubectl-proxy
          image: palmstonegames/kubectl-proxy:{{ .Values.kubectlVersion }}
      volumes:
        - name: "data"
          gcePersistentDisk:
            pdName: kube-cert-manager
            fsType: ext4
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https # Todo: Test if this works.
          containerPort: 8081
          protocol: TCP
