---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "google-cloud"
  namespace: {{ default "default" .Values.namespace | quote }}
data:
  credentials.json: {{ default "{}" .Values.googleApplicationCredentials | b64enc | quote }}
