---
## The URL to the ACME server that's issuing the certificates.
## ref: https://github.com/PalmStoneGames/kube-cert-manager/blob/master/docs/deployment-guide.md#deployment-guide
acmeUrl: "https://acme-staging.api.letsencrypt.org/directory"

## The version of the kubectl client to use. If you're using a 1.3 cluster version, change this to 1.3.6
## ref: https://github.com/PalmStoneGames/kube-cert-manager/blob/master/docs/deployment-guide.md#deployment-guide
kubectlVersion: "1.4.0"

## Change the namespace the certificate manager is deployed to
deploymentNamespace: "default"

# CLOUDFLARE
cloudflareEmail: ""
cloudflareApiKey: ""
#
# DIGITAL OCEAN
doAuthToken: ""
#
# DNSIMPlE
dnsimpleEmail: ""
dnsimpleApiKey: ""
#
# DNS MADE EASY
dnsmadeeasyApiKey: ""
dnsmadeeasyApiSecret: ""
dnsmadeeasySandbox: ""
#
# DYN
dynCustomerName: ""
dynUserName: ""
dynPassword: ""
#
# GANDI
gandiApiKey: ""
#
# GOOGLE CLOUD
gceProject: ""
googleApplicationCredentials: ""
#
# NAMECHEAP
namecheapApiUser: ""
namecheapApiKey: ""
#
# OVH
ovhEndpoint: ""
ovhApplicationKey: ""
ovhApplicationSecret: ""
ovhConsumerKey: ""
#
# PDNS
pdnsApiKey: ""
#
# RFC2136
rfc2136Nameserver: ""
rfc2136TsigAlgorithm: ""
rfc2136TsigKey: ""
rfc2136TsigSecret: ""
#
# AMAZON ROUTE 53
awsAccessKey: ""
awsSecretAccessKey: ""
#
# VULTR
vultrApiKey: ""
